apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ad
- ./cart
- ./checkout
- ./currency
- ./email
- ./frontend
- ./loadgenerator
- ./payments
- ./productcatalog
- ./recommendation
- ./rediscart
- ./shipping
commonAnnotations:
  ManagedBy: ArgoCD